#production not ready
spring:
  application:
    name: jounralrestapi
  data:
    mongodb:
      uri: mongodb+srv://vcartproject:DN7YRhfpnHMN0o9B@cluster0.al87hbm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: MAIL_USERNAME
    password: MAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080
  servlet:
    context-path: "/somnath"


weather:
  api:
    key: 9c06f19f893bc84ecd48d20cc3c364ad