#production not ready
spring:
  application:
    name: jounralrestapi
  data:
    mongodb:
      uri: mongodb+srv://vcartproject:DN7YRhfpnHMN0o9B@cluster0.al87hbm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true


server:
  port: 8082
  servlet:
    context-path: "/somnath"