#production not ready
spring:
  application:
    name: jounralrestapi
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb+srv://vcartproject:DN7YRhfpnHMN0o9B@cluster0.al87hbm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    #username: somnathv.nalawade@gmail.com
    username: ${MAIL_USERNAME}
    #password: zbdpwqiblesejkap
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080
  servlet:
    context-path: "/somnath"


weather:
  api:
    key: 9c06f19f893bc84ecd48d20cc3c364ad